### ISSUE TITLE
issues with compress files

### ISSUE THREAD

**Issue by Quickgold74** [libretro/TempGBA-libretro#2]
when try to open a rom (zip) PSP freeze and crash, RA had this issue under PSP since older nightlies 1.31 until the last version.

**Comment by bmaupin** [comment]
This is an interesting bug because this should be handled by RetroArch and not the core.

I can open any zip file just fine and browse to the ROM. Some ROMs in a zip load fine and others don't.

The only thing I've been able to figure out so far is that ROMs that have an uncompressed size of 1 MB or less seem to load fine, such as the GBA test suite ROM from here: https://forums.mgba.io/showthread.php?tid=18

ROMs that have an uncompressed size of 4 MB or more (I couldn't find any 2 MB ROMs) all fail with `Could not read content file`:

```
[INFO] Using content: ms0:/PSP/RETROARCH/Games/metroidzeromission.zip#metroidzeromission.gba.
[INFO] arg #0: retroarch
[INFO] arg #1: ms0:/PSP/RETROARCH/Games/metroidzeromission.zip#metroidzeromission.gba
[INFO] arg #2: -s
[INFO] arg #3: ms0:/PSP/RETROARCH/SAVEFILES
[INFO] arg #4: -S
[INFO] arg #5: ms0:/PSP/RETROARCH/SAVESTATES
[INFO] arg #6: -c
[INFO] arg #7: ms0:/PSP/RETROARCH/retroarch.cfg
[INFO] arg #8: -v
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] Unloading game..
[INFO] Unloading core..
[INFO] Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] Set config file to : ms0:/PSP/RETROARCH/retroarch.cfg
[INFO] Redirecting save file to "ms0:/PSP/RETROARCH/SAVEFILES/metroidzeromission.srm".
[INFO] Redirecting savestate to "ms0:/PSP/RETROARCH/SAVESTATES/metroidzeromission.state".
[INFO] === Build =======================================
[INFO] Capabilities: VFPU 
[INFO] Built: May  8 2019
[INFO] Version: 1.7.7
[INFO] =================================================
[INFO] [Overrides] no core-specific overrides found at ms0:/PSP/RETROARCH/CONFIG/TempGBA/TempGBA.cfg.
[INFO] [Overrides] no content-dir-specific overrides found at ms0:/PSP/RETROARCH/CONFIG/TempGBA/Games.cfg.
[INFO] [Overrides] no game-specific overrides found at ms0:/PSP/RETROARCH/CONFIG/TempGBA/metroidzeromission.cfg.
[INFO] Environ GET_LOG_INTERFACE.
[INFO] Environ GET_PERF_INTERFACE.
[INFO] [Remaps]: remap directory: ms0:/PSP/RETROARCH/CONFIG/REMAPS
[INFO] [Remaps]: no game-specific remap found at ms0:/PSP/RETROARCH/CONFIG/REMAPS/TempGBA/metroidzeromission.rmp.
[INFO] [Remaps]: no content-dir-specific remap found at ms0:/PSP/RETROARCH/CONFIG/REMAPS/TempGBA/Games.rmp.
[INFO] [Remaps]: no core-specific remap found at ms0:/PSP/RETROARCH/CONFIG/REMAPS/TempGBA/TempGBA.rmp.
[INFO] Redirecting save file to "ms0:/PSP/RETROARCH/SAVEFILES/metroidzeromission.srm".
[INFO] Redirecting savestate to "ms0:/PSP/RETROARCH/SAVESTATES/metroidzeromission.state".
[INFO] Compressed file in case of need_fullpath. Now extracting to temporary directory.
[ERROR] Could not read content file "ms0:/PSP/RETROARCH/Games/metroidzeromission.zip#metroidzeromission.gba".
```

I see this core has `need_fullpath = true`, so one possible fix could be to modify the core so `need_fullpath` can be set to false. But given that GBA ROMs can be as large as 32 MB and the PSP only has 32 MB of RAM, is that even possible?

**Comment by bmaupin** [comment]
More testing: I saw that [mGBA has `need_fullpath = false`](https://github.com/libretro/mgba/blob/9c8a1a598d04e764df5f848ff619869a9c3f6ad8/src/platform/libretro/libretro.c#L439) so I was curious whether it could handle these large ROMs.

mGBA on PSP seems to be able to run most compressed ROMs, but it can't load ROMs whose uncompressed size is 32 MB. I tested with four different 32 MB ROMs:

- Bleach Advance
- Kingdom Hearts: Chain of Memories
- Riviera: The Promised Land
- The Urbz: Sims in the City

When trying to load any of those ROMs from zip files in RetroArch with mGBA, they all fail to load.

```
[INFO] Loading content file: ms0:/PSP/RETROARCH/Games/test/32mb/1757 - The Urbz - Sims in the City (E)(Rising Sun).zip#1757 - The Urbz - Sims in the City (E)(Rising Sun).gba.
[INFO] Did not find a valid content patch.
[INFO] CRC32: 0x0 .
[ERROR] Failed to load content.
```

When trying to load any of those ROMs from .gba files with mGBA, the PSP completely crashes and loses power. I didn't see anything helpful in the logs, so maybe it just ran out of memory?:

```
[INFO] Redirecting save file to "ms0:/PSP/RETROARCH/SAVEFILES/1757 - The Urbz - Sims in the City (E)(Rising Sun).srm".
[INFO] Redirecting savestate to "ms0:/PSP/RETROARCH/SAVESTATES/1757 - The Urbz - Sims in the City (E)(Rising Sun).state".
[INFO] === Build =======================================
[INFO] Capabilities: VFPU 
[INFO] Built: May  8 2019
[INFO] Version: 1.7.7
[INFO] =================================================
[INFO] [Overrides] no core-specific overrides found at ms0:/PSP/RETROARCH/CONFIG/mGBA/mGBA.cfg.
[INFO] [Overrides] no content-dir-specific overrides found at ms0:/PSP/RETROARCH/CONFIG/mGBA/32mb.cfg.
[INFO] [Overrides] no game-specific overrides found at ms0:/PSP/RETROARCH/CONFIG/mGBA/1757 - The Urbz - Sims in the City (E)(Rising Sun).cfg.
[INFO] Environ SET_VARIABLES.
[INFO] [Remaps]: remap directory: ms0:/PSP/RETROARCH/CONFIG/REMAPS
[INFO] [Remaps]: no game-specific remap found at ms0:/PSP/RETROARCH/CONFIG/REMAPS/mGBA/1757 - The Urbz - Sims in the City (E)(Rising Sun).rmp.
[INFO] [Remaps]: no content-dir-specific remap found at ms0:/PSP/RETROARCH/CONFIG/REMAPS/mGBA/32mb.rmp.
[INFO] [Remaps]: no core-specific remap found at ms0:/PSP/RETROARCH/CONFIG/REMAPS/mGBA/mGBA.rmp.
[INFO] Redirecting save file to "ms0:/PSP/RETROARCH/SAVEFILES/1757 - The Urbz - Sims in the City (E)(Rising Sun).srm".
[INFO] Redirecting savestate to "ms0:/PSP/RETROARCH/SAVESTATES/1757 - The Urbz - Sims in the City (E)(Rising Sun).state".
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, User 1, Button "B (bottom)" => "B"
[INFO] 	RetroPad, User 1, Button "Y (left)" => "Turbo B"
[INFO] 	RetroPad, User 1, Button "Select" => "Select"
[INFO] 	RetroPad, User 1, Button "Start" => "Start"
[INFO] 	RetroPad, User 1, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 1, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 1, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 1, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, User 1, Button "A (right)" => "A"
[INFO] 	RetroPad, User 1, Button "X (up)" => "Turbo A"
[INFO] 	RetroPad, User 1, Button "L" => "L"
[INFO] 	RetroPad, User 1, Button "R" => "R"
[INFO] 	RetroPad, User 1, Button "L2" => "Turbo L"
[INFO] 	RetroPad, User 1, Button "R2" => "Turbo R"
[INFO] 	RetroPad, User 1, Button "L3" => "Darken Solar Sensor"
[INFO] 	RetroPad, User 1, Button "R3" => "Brighten Solar Sensor"
[INFO] Environ GET_RUMBLE_INTERFACE.
[INFO] Environ GET_LOG_INTERFACE.
[INFO] Loading content file: ms0:/PSP/RETROARCH/Games/test/32mb/1757 - The Urbz - Sims in the City (E)(Rising Sun).gba.
```

However, all of those 32 MB ROMs load fine with the TempGBA core.

My original thought was to see if it'd be possible to rewrite the TempGBA core so that it can work with `need_fullpath = false`. But at this point, my fear is that after spending all that time to get it working, TempGBA might end up with the same behaviour as mGBA (able to load compressed ROMs >= 4 MB but unable to load any 32 MB ROMs, compressed or uncompressed).

Given the PSP only has 32 MB of memory, I'm wondering if it'd be best to disable TempGBA's ability to load ROMs from zip files altogether.

**Comment by bmaupin** [comment]
I can think of a few options:

- Rewrite the core so it can work with `need_fullpath = false`. My very limited understanding of the code tells me this won't work with large ROMs because of memory limitations, for example: https://github.com/libretro/TempGBA-libretro/blob/f69fc6c5cb869b63beb82fc3af644ac59fec070d/memory.c#L2610-L2611

- Figure out how to fix this issue in RetroArch itself. My best guess is however RetroArch loads compressed ROMs needs some extra massaging for the PSP and its limited memory.

- Add the logic back to the core for loading zip files that was removed in 084afce4. This definitely seems like the easiest approach.

@twinaphex How do you think this should be handled? I'd be willing to give the last option a shot (no guarantees I'll actually get it to work), but I don't think I have the ability to tackle the other two.

**Comment by bmaupin** [comment]
Since I think this is ultimately an issue with RetroArch, I've filed bug https://github.com/libretro/RetroArch/issues/9143

In the meantime, I'll see if I can add the zip functionality back to the core itself to at least fix this partially.
